# Generated by Django 5.0.14 on 2026-08-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="reason",
            field=models.CharField(
                choices=[
                    ("referral_bonus", "Referral Bonus"),
                    ("order_payment", "Used on Order"),
                    ("delivery_bonus", "Delivery Bonus"),
                    ("adjustment", "Manual Adjustment"),
                ],
                max_length=20,
            ),
        ),
    ]
