# Generated by Django 5.0.14 on 2026-08-10 10:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_replace_referral_percentage_with_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralsettings",
            name="delivery_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20.00"),
                help_text="Delivery charge applied below the free-delivery threshold.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="referralsettings",
            name="free_delivery_minimum",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("200.00"),
                help_text="Orders at or above this amount get free delivery.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="referralsettings",
            name="minimum_order_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Orders below this amount cannot be placed.",
                max_digits=8,
            ),
        ),
    ]
