# Generated by Django 5.0.14 on 2026-08-10 11:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_referralsettings_delivery_charge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralsettings",
            name="free_delivery_minimum",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100.00"),
                help_text="Orders at or above this amount get free delivery.",
                max_digits=8,
            ),
        ),
    ]
