# Generated by Django 5.0.14 on 2026-08-06 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_emoji', models.CharField(blank=True, help_text='e.g. 🥬', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit_type', models.CharField(choices=[('weight', 'Weight (kg/g)'), ('piece', 'Piece / Count')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_organic', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_unit', models.CharField(blank=True, choices=[('g', 'grams'), ('kg', 'kilograms')], max_length=2, null=True)),
                ('piece_count', models.PositiveIntegerField(blank=True, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Strike-through price', max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=8)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['product', 'price'],
            },
        ),
    ]
