# Generated by Django 5.0.14 on 2026-08-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Cash on Delivery"),
                    ("online", "Online (Razorpay)"),
                    ("wallet", "Wallet"),
                ],
                default="cod",
                max_length=10,
            ),
        ),
    ]
