# Generated by Django 5.0.14 on 2026-08-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_bonus",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_speed",
            field=models.CharField(
                choices=[
                    ("instant", "Instant"),
                    ("3_4_hours", "3-4 hours"),
                    ("next_day", "Next day"),
                ],
                default="instant",
                max_length=20,
            ),
        ),
    ]
