# Generated by Django 5.0.14 on 2026-08-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_delivery_bonus_order_delivery_speed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_speed",
            field=models.CharField(
                choices=[
                    ("instant", "Instant"),
                    ("2_4_hours", "2-4 Hours"),
                    ("next_day_morning", "Next day Morning"),
                ],
                default="instant",
                max_length=20,
            ),
        ),
    ]
